<a href="https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Atividade_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
# ATV 11
# A "TechGadgets Ltda." é uma empresa de tecnologia que vende diversos produtos eletrônicos.
# Você foi contratado para analisar o desempenho de vendas nos últimos meses,
# identificar tendências e visualizar os resultados.
# A empresa está interessada em entender as vendas totais,
# a distribuição das vendas por categoria de produto e a variação mensal.
import numpy as np
import pandas as pd
import statistics as st
# Exercício: Desempenho de Vendas e Análise de Produtos

In [112]:
# Geração de Dados Sintéticos (NumPy e Pandas):
# Utilize numpy para gerar os seguintes dados:
# meses: Um array de 12 meses (de 1 a 12) representando um ano.

In [113]:
meses = np.arange(1, 13)
meses

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [114]:
# vendas_produto_A: Um array de 12 valores de vendas para o "Produto A",
# com média de 1000 e desvio padrão de 150 (use np.random.normal).
# Certifique-se de que não há vendas negativas (arredonde para cima ou defina como 0 se for negativo).

In [115]:
vendas_A = np.random.normal(loc=1000, scale=150, size=12)
vendas_A = np.where(vendas_A < 0, 0, np.ceil(vendas_A))
vendas_A

array([1030.,  761.,  946., 1015.,  828.,  911., 1109.,  953., 1109.,
       1012.,  978., 1068.])

In [116]:
# vendas_produto_B: Um array de 12 valores de vendas para o "Produto B",
# com média de 800 e desvio padrão de 100.

In [117]:
vendas_B = np.random.normal(loc=800, scale=100, size=12)
vendas_B = np.where(vendas_B <0, 0, np.ceil(vendas_B))
vendas_B

array([ 748.,  975.,  826.,  892.,  877., 1003.,  915.,  806.,  914.,
        978.,  691.,  878.])

In [118]:
# vendas_acessorios: Um array de 12 valores de vendas para "Acessórios",
# com média de 300 e desvio padrão de 50

In [119]:
vendas_acc = np.random.normal(loc=300, scale=50, size=12)
vendas_acc = np.where(vendas_acc < 0, 0, np.ceil(vendas_acc))
vendas_acc

array([435., 301., 203., 313., 350., 272., 229., 278., 345., 319., 396.,
       309.])

In [120]:
# Crie um DataFrame Pandas chamado df_vendas com as seguintes colunas: 'Mês', 'Produto A', 'Produto B', 'Acessórios'.

In [121]:
df_vendas = pd.DataFrame({'Mês': meses, 'Produto A': vendas_A, 'Produto B': vendas_B, 'Acessórios': vendas_acc})
df_vendas

Mês  Produto A  Produto B  Acessórios
0     1     1030.0      748.0       435.0
1     2      761.0      975.0       301.0
2     3      946.0      826.0       203.0
3     4     1015.0      892.0       313.0
4     5      828.0      877.0       350.0
5     6      911.0     1003.0       272.0
6     7     1109.0      915.0       229.0
7     8      953.0      806.0       278.0
8     9     1109.0      914.0       345.0
9    10     1012.0      978.0       319.0
10   11      978.0      691.0       396.0
11   12     1068.0      878.0       309.0

In [122]:
# Cálculos e Análise (Pandas):

# Adicione uma nova coluna ao df_vendas chamada 'Total Vendas Mensal',
# que será a soma das vendas de 'Produto A', 'Produto B' e 'Acessórios' para cada mês.
# Calcule e exiba a média de vendas de cada produto ('Produto A', 'Produto B', 'Acessórios') e do 'Total Vendas Mensal' para todo o período.
# Calcule e exiba o valor total de vendas para cada categoria de produto
# ('Produto A', 'Produto B', 'Acessórios') e o 'Total Vendas Mensal' acumulado.
# Identifique e exiba o mês com o maior 'Total Vendas Mensal'.
# Identifique e exiba o mês com a menor 'Total Vendas Mensal'

In [123]:
df_vendas['Total Vendas Mensal'] = df_vendas['Produto A'] + df_vendas['Produto B'] + df_vendas['Acessórios']
df_vendas

Mês  Produto A  Produto B  Acessórios  Total Vendas Mensal
0     1     1030.0      748.0       435.0               2213.0
1     2      761.0      975.0       301.0               2037.0
2     3      946.0      826.0       203.0               1975.0
3     4     1015.0      892.0       313.0               2220.0
4     5      828.0      877.0       350.0               2055.0
5     6      911.0     1003.0       272.0               2186.0
6     7     1109.0      915.0       229.0               2253.0
7     8      953.0      806.0       278.0               2037.0
8     9     1109.0      914.0       345.0               2368.0
9    10     1012.0      978.0       319.0               2309.0
10   11      978.0      691.0       396.0               2065.0
11   12     1068.0      878.0       309.0               2255.0

In [138]:
vendas_max = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmax()]
vendas_max

Mês                       9.0
Produto A              1109.0
Produto B               914.0
Acessórios              345.0
Total Vendas Mensal    2368.0
Name: 8, dtype: float64

In [147]:
vendas_min = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmin()]
vendas_min

Mês                       3.0
Produto A               946.0
Produto B               826.0
Acessórios              203.0
Total Vendas Mensal    1975.0
Name: 2, dtype: float64